### PR TITLE
Add Faber-Castell Polychromos 60- and 120-color sets

### PR DESCRIPTION
**Pull request by SmithsonianDSP**
Please add the 60- and 120-color palettes of Faber-Castell Polychromos colored pencils to the list of available color sets. 

Color lists were pulled from the product descriptions on dickblick.com ([Set of 60](https://www.dickblick.com/items/faber-castell-polychromos-pencil-set-assorted-colors-tin-box-set-of-60/) & [Set of 120](https://www.dickblick.com/items/faber-castell-polychromos-pencil-set-assorted-colors-set-of-120/))

### CODE REVIEW

**Comment by eugene-khyst** [comment]
Hi @SmithsonianDSP,
Thanks for the pull request.
At the moment, number of colors is limited to 36 because for watercolor, acrylics and oil 2 and 3 color mixes are prepared. Combinations of 3 colors among 120 colors in multiple ratios - too many mixes to fit in memory.
Thus, I need to adjust the Color set tab logic.

**Comment by SmithsonianDSP** [comment]
This is only for colored pencils where there isn't any mixing required. And I can already select all 120+ of the Polychromos colors in the tool; this would just save me (and others) from making an extra 60-120 clicks to select all of them.

**Comment by eugene-khyst** [comment]
@SmithsonianDSP, yes, you are right, I just have to change the information message.
Thanks for the contribution, merging the PR.

**Comment by eugene-khyst** [comment]
Added even more pencil sets of different brands in #9

**Pull request closed without merging**
